finished lab and exercises
unable to push:

(base) KristensMacBook:python_intro kristentokunaga$ git add .
(base) KristensMacBook:python_intro kristentokunaga$ git add python_review_and_best_practices.ipynb
(base) KristensMacBook:python_intro kristentokunaga$ git commit -m "finished lessons and exercises"
On branch intro_to_git_branches
nothing to commit, working tree clean
(base) KristensMacBook:python_intro kristentokunaga$ cd dsp
-bash: cd: dsp: No such file or directory
(base) KristensMacBook:python_intro kristentokunaga$ cd ..
(base) KristensMacBook:lessons kristentokunaga$ cd ..
(base) KristensMacBook:dsp kristentokunaga$ cd lessons/
(base) KristensMacBook:lessons kristentokunaga$ 
(base) KristensMacBook:lessons kristentokunaga$ cd python_intro/
(base) KristensMacBook:python_intro kristentokunaga$ git init
Initialized empty Git repository in /Users/kristentokunaga/Documents/NewFolderName/MetisCourseMaterials/dsp/lessons/python_intro/.git/
(base) KristensMacBook:python_intro kristentokunaga$ ls -a
.					instructor_guide_week1_day1.md
..					python_review_and_best_practices.ipynb
.git					questions
.ipynb_checkpoints			readme.md
importing_with_python
(base) KristensMacBook:python_intro kristentokunaga$ git log
fatal: your current branch 'master' does not have any commits yet
(base) KristensMacBook:python_intro kristentokunaga$ git add python_review_and_best_practices.ipynb
(base) KristensMacBook:python_intro kristentokunaga$ git commit -m "finished lesson and exercises" 
[master (root-commit) 5212384] finished lesson and exercises
 1 file changed, 2306 insertions(+)
 create mode 100644 python_review_and_best_practices.ipynb
(base) KristensMacBook:python_intro kristentokunaga$ git push
fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>

(base) KristensMacBook:python_intro kristentokunaga$ git remote add origin https://github.com/kristentaytok/dsp
(base) KristensMacBook:python_intro kristentokunaga$ git remote -v
origin	https://github.com/kristentaytok/dsp (fetch)
origin	https://github.com/kristentaytok/dsp (push)
(base) KristensMacBook:python_intro kristentokunaga$ git push origin master
To https://github.com/kristentaytok/dsp
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/kristentaytok/dsp'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.